name: local_storage_contacts_api
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  contacts_api:
    path: ../contacts_api
  flutter:
    sdk: flutter
  meta: ^1.7.0
  rxdart: ^0.27.3
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0
